youtube_channels = [
  %{
    instagram_id: "digital.harmonic",
    twitter_id: "iamzheanna",
    youtube_id: "UC--VosYH0BHISbb4SFO9rQA",
    name: "Zheanna Erose"
  },
  %{
    instagram_id: "o_jack",
    twitter_id: "_ojack_",
    youtube_id: "UC-2LWDrIxHOd2mnt1RHbzrg",
    name: "Olivia Jack"
  },
  %{
    instagram_id: "benawad97",
    twitter_id: "benawad",
    youtube_id: "UC-8QAzbLcRglXeN_MY9blyw",
    name: "Ben Awad"
  },
  %{youtube_id: "UC-8Uff7i2h5qtIvjXJDJqYA", name: "Minhas Plantas"},
  %{youtube_id: "UC-ZX7WqyBL9k1OO7jCtIZQA", name: "쿄쿄쿜"},
  %{youtube_id: "UC-id0vwQoAUYBNCm0nmaqQw", name: "Alex McLean"},
  %{youtube_id: "UC02coXfDPjEmU8uDT2G8Z2A", name: "Jones Manoel"},
  %{youtube_id: "UC033rpv7OKk-QYfrvwl5s8Q", name: "TV Quase"},
  %{youtube_id: "UC0656iccvdiHrNvw6T-SYyA", name: "floodcomics"},
  %{youtube_id: "UC0KUAHng0_ZnuM1sDntJX2Q", name: "tritenina"},
  %{youtube_id: "UC0NpEEcmONWuTU3nfURmyKw", name: "A&P-REACTS"},
  %{youtube_id: "UC0X7Mjk9NuEHFqxu_xasveg", name: "Cubo Itaú"},
  %{
    instagram_id: "notjustbikes",
    twitter_id: "notjustbikes",
    youtube_id: "UC0intLFzLaudFG-xAvUEO-A",
    name: "Not Just Bikes"
  },
  %{youtube_id: "UC15UOu9F157NAXGL9dHc4TQ", name: "Dmitry Soshnikov"},
  %{youtube_id: "UC190_sCiYfgqRveTMtBcdpQ", name: "djalgoritmo"},
  %{youtube_id: "UC1DTYW241WD64ah5BFWn4JA", name: "Sam O'Nella Academy"},
  %{youtube_id: "UC1IvDDy7kNh8VPyziZhb5Lw", name: "Marginalia"},
  %{youtube_id: "UC1dkDvk6PbogiO_YWzdKUwA", name: "Soundway Records"},
  %{youtube_id: "UC28n0tlcNSa1iPe5mettocg", name: "voidzilla"},
  %{
    instagram_id: "philosophy.tube",
    twitter_id: "PhilosophyTube",
    tiktok_id: "theabigailthorn",
    youtube_id: "UC2PA-AKmVpU6NKCGtZq_rKQ",
    name: "Philosophy Tube"
  },
  %{youtube_id: "UC2Xd-TjJByJyK2w1zNwY0zQ", name: "Beyond Fireship"},
  %{youtube_id: "UC2mT7quMGAx5wPsARspOGIA", name: "Marina Sena"},
  %{youtube_id: "UC2p7hQGQ7BG1UUQjEqHHvVA", name: "Bernard Gray"},
  %{youtube_id: "UC2xRKIX2m_oytPA2izBZTcQ", name: "Ely Janoville"},
  %{youtube_id: "UC3-qKkfX0sa99FHPS4EQ0yA", name: "Tory Slusher"},
  %{youtube_id: "UC33fpxyEKncrK1EgfL_HIKQ", name: "Hugo Rangel"},
  %{youtube_id: "UC349-wZQKtpaCWZk2j1meXQ", name: "FutureStops"},
  %{youtube_id: "UC36P4Z70NeFfA4OPKiJ7oPw", name: "INDEX"},
  %{youtube_id: "UC38xbd3KhfU8afjOQiix35A", name: "Céu (Oficial)"},
  %{youtube_id: "UC3bTu_4BtpfdiUMKMix7V-g", name: "Andy R"},
  %{youtube_id: "UC3eHpzW-Nhfx6Uf6nSxuDhw", name: "Rafrobeat"},
  %{
    instagram_id: "prof_humberto_matos",
    twitter_id: "H1SaiaDaMatrix",
    youtube_id: "UC3qAUf53j_dUv09jH7jsUJw",
    name: "Humberto Matos"
  },
  %{
    instagram_id: "cortesdocasimiro",
    twitter_id: "cortesdocaze",
    youtube_id: "UC4aiJNDUviw_vMhdCq5Kq1Q",
    name: "Cortes do Casimito [OFICIAL]"
  },
  %{youtube_id: "UC4s4I_0RxKMgp-HKRVagRnw", name: "Nick Keomahavong"},
  %{
    instagram_id: "felipe.durante",
    twitter_id: "fedurante",
    youtube_id: "UC53tme8fwwfiNs8WubMwC6g",
    name: "Felipe Durante pelo mundo"
  },
  %{youtube_id: "UC57gLBfdhN1zWMLmiW2Ya6Q", name: "Think That Through"},
  %{youtube_id: "UC59L9n7Xvdc-p1fWuYkz0ZA", name: "Leah's Fieldnotes"},
  %{
    twitter_id: "MrGervaisWrites",
    youtube_id: "UC5CYeHPLer3lbEhgonvbbAA",
    name: "Noah Caldwell-Gervais"
  },
  %{youtube_id: "UC5KD9-xh1dIlX4qjQs0VLjQ", name: "Jack Armitage (jarm)"},
  %{youtube_id: "UC5bpDi-V_e3S3VN5I2tIYCA", name: "Bitkids"},
  %{
    twitter_id: "innuendostudios",
    youtube_id: "UC5fdssPqmmGhkhsJi4VcckA",
    name: "Innuendo Studios"
  },
  %{youtube_id: "UC5ojw47w3F8Ift7RlOt9vWg", name: "GAVI Music"},
  %{youtube_id: "UC5sMjGaQJXkQdZTzGkSjYDg", name: "Nômade Raiz"},
  %{youtube_id: "UC5skJN2WYbyYHUmrMQ00LtA", name: "Mike Hodnick"},
  %{youtube_id: "UC6-MiE_-4D-wWZVJwOZrzeA", name: "DSC LAB RP Digital"},
  %{
    instagram_id: "wisecrack_official",
    twitter_id: "wisecrack",
    youtube_id: "UC6-ymYjG0SU0jUWnWh9ZzEQ",
    name: "Wisecrack"
  },
  %{youtube_id: "UC6IxnFzHofFJ5X2PycSMsww", name: "xkcd's What If?"},
  %{youtube_id: "UC6iiSl-DJQF5t_YttyUZX6Q", name: "Podcast 3 irmãos"},
  %{youtube_id: "UC6tBJZdzl15ui6jmbQ1SFJA", name: "Christos Benetatos"},
  %{
    instagram_id: "assimdisseojoao",
    twitter_id: "assimdisseojoao",
    tiktok_id: "assimdisseojoao",
    youtube_id: "UC7-Pp09PJX_SYP9oyMzUAtg",
    name: "João Carvalho"
  },
  %{
    instagram_id: "pgdinamica",
    twitter_id: "pgdinamica",
    youtube_id: "UC70mr11REaCqgKke7DPJoLg",
    name: "Programação Dinâmica"
  },
  %{
    instagram_id: "podsdank",
    twitter_id: "PodsDank",
    youtube_id: "UC7Jwj9fkrf1adN4fMmTkpug",
    name: "DankPods"
  },
  %{youtube_id: "UC7VnJ1oTlPdo9wrI71s9V9w", name: "Desdemona ETC - Topic"},
  %{youtube_id: "UC7YOGHUfC1Tb6E4pudI9STA", name: "Mental Outlaw"},
  %{youtube_id: "UC84u8v2FyqmXjSxYh1d7PRQ", name: "acreil"},
  %{youtube_id: "UC8FfmwtF0z-JmXs3JTiBFQQ", name: "Loose Leaf Tea Market"},
  %{youtube_id: "UC8J4hTAPsn1PUpYK-apm_eg", name: "Homeostasis Lab"},
  %{youtube_id: "UC8SisRxGJhcy0LpZnWVgvfQ", name: "Iris Saladino"},
  %{youtube_id: "UC8TZwtZ17WKFJSmwTZQpBTA", name: "MAJ"},
  %{youtube_id: "UC8_l_QGcW6gDw2KBzQ4VZSA", name: "Djembe Guru"},
  %{youtube_id: "UC8fqt_PDhDDszL5Zi8EauqA", name: "Terminal Passage"},
  %{youtube_id: "UC8gGIw-shIcknbdMvwrcKRQ", name: "Levi McClain"},
  %{youtube_id: "UC8gbbVMUmEDpd-rqVGL_zYA", name: "fluidvolt"},
  %{youtube_id: "UC8ha68gfkmh5v2a2BAx7low", name: "DThompsonDev"},
  %{youtube_id: "UC8lWmqYay4Yqb9aRnAWTkNw", name: "Remrug - Topic"},
  %{youtube_id: "UC8o26sJe1eXdQkBjwT-krzQ", name: "NTHLCRVLH ϟ"},
  %{youtube_id: "UC8ya7uaEIuwo3lRn54gpRZw", name: "Brazilian Rare Grooves"},
  %{youtube_id: "UC9-5U4dP1ZUDQxqmsh-kcQg", name: "FRENTE CUMBIERO"},
  %{youtube_id: "UC96_Jh8sockkCnKnYrE7uWQ", name: "Pedro Miranda"},
  %{youtube_id: "UC97VWzYLwjEIDfoXmdub-2Q", name: "VLSkate"},
  %{youtube_id: "UC9GU23jlPOZHGXk2Gm-3plQ", name: "Joo Won Park"},
  %{
    instagram_id: "wendoverproductions",
    twitter_id: "wendoverpro",
    youtube_id: "UC9RM-iSvTu1uPJb8X5yp3EQ",
    name: "Wendover Productions"
  },
  %{youtube_id: "UC9TfgtLt0500BXqPVVmfuTA", name: "Pull Request"},
  %{
    instagram_id: "aragusea",
    twitter_id: "aragusea",
    youtube_id: "UC9_p50tH3WmMslWRWKnM7dQ",
    name: "Adam Ragusea"
  },
  %{youtube_id: "UC9eHqcMwKKQ60enNyJuKssA", name: "kriyananda"},
  %{youtube_id: "UC9xSeav-AN2DJVtHdpKlb1g", name: "Lais Veludo"},
  %{youtube_id: "UCAAZJ9SX0RZ9AiAToF6ebjA", name: "Giada LoopMachine"},
  %{youtube_id: "UCADUySasvSqmTewWq03ESyA", name: "Sun Ceremonies"},
  %{youtube_id: "UCAEDPwL_Ws3CJl-KMLWNNbg", name: "Manuela d'Ávila"},
  %{
    instagram_id: "historiapublica_",
    twitter_id: "ianfneves",
    youtube_id: "UCAMExYqcweM7PUebKfmLdFA",
    name: "Ian Neves"
  },
  %{youtube_id: "UCAeZgseUaAmIAyHOg1Yx-6g", name: "Diego Dorado"},
  %{youtube_id: "UCAuiibpcf93bv3tJoCEaAKg", name: "podcast mais um rolê"},
  %{youtube_id: "UCAyUmS4ewvyqvkgQyLVmyWA", name: "playpm"},
  %{youtube_id: "UCAzPN3ilUBKEU0hcQ0vuxpw", name: "George Secor"},
  %{youtube_id: "UCB2qpWIeZ0WaeLo8i9woyAA", name: "Corserine"},
  %{youtube_id: "UCBUgloGcRYTtuFfkjwImG4Q", name: "gmcfosho"},
  %{
    instagram_id: "tomscottgo",
    twitter_id: "tomscott",
    youtube_id: "UCBa659QWEk1AI4Tg--mrJ2A",
    name: "Tom Scott"
  },
  %{youtube_id: "UCBn1rFRrUXLDpMhLHnwX3mQ", name: "VGM Real Book"},
  %{
    instagram_id: "descealetrashow",
    twitter_id: "DesceALetraShow",
    youtube_id: "UCCD93px0UneWNFg_HxV4naQ",
    name: "DESCE A LETRA SHOW"
  },
  %{youtube_id: "UCCkLMimnKzKbOQYxPDSYXFw", name: "samyam"},
  %{youtube_id: "UCCr9mFiNcGVzeXzfmwfqxiQ", name: "Samuel Pearce-Davies"},
  %{youtube_id: "UCCvGd1WBMpFQ_vtC89VF2qA", name: "Aurélien Géron"},
  %{youtube_id: "UCDDQ2uQJ7mI5vcMeHD9oWjw", name: "Little Heroes"},
  %{youtube_id: "UCDDobgQYZHvlYqwnuGE1B7w", name: "hello erika"},
  %{youtube_id: "UCDIGnIniKSa2VycykUK83Zg", name: "NicheAudities"},
  %{youtube_id: "UCDoH9PG9-3-IIW8wDfsm4Tg", name: "DRMR"},
  %{
    instagram_id: "guitarlaurenceharrison",
    youtube_id: "UCDqaefcFrSnkKFZwIrKk4Fw",
    name: "Laurence Harrison"
  },
  %{youtube_id: "UCED1QpeMYP4apdCVGjBqhCg", name: "ELLYACADEMY"},
  %{youtube_id: "UCEDkO7wshcDZ7UZo17rPkzQ", name: "mayuko"},
  %{youtube_id: "UCEeNJvSplCddJc9oSdxj9Ig", name: "Exarch Foobaru"},
  %{youtube_id: "UCEwiNHuPF1Q7HbRLarxov8g", name: "Yung Jake"},
  %{
    instagram_id: "phillip_mcknight",
    twitter_id: "askknowyourgear",
    youtube_id: "UCEzJtFWNg7d7TZW7K9JyXmw",
    name: "Phillip McKnight"
  },
  %{youtube_id: "UCF2gfMq06jskM5dPnHVsNtQ", name: "Normal Universe - Chris Guichet"},
  %{youtube_id: "UCF3Dfrk2mtSlTjdXQ8KF8Dw", name: "Deep Drumz Records"},
  %{youtube_id: "UCF6VjYfikYP2vfUx3c6GvVw", name: "Christian Dunker"},
  %{youtube_id: "UCFJhd5QU__Z5CIy8Ixp4wuw", name: "Garoto - Topic"},
  %{youtube_id: "UCFMcaOlrV9IgOTpjGn_cIww", name: "Georgia Tech Center for Music Technology"},
  %{
    instagram_id: "coffeebreak_yt",
    twitter_id: "coffeebreak_YT",
    youtube_id: "UCFQMnBA3CS502aghlcr0_aw",
    name: "Coffeezilla"
  },
  %{youtube_id: "UCFRw4fgQb7dqRXuZ5lxwi3g", name: "The Society for Nontrivial Pursuits"},
  %{youtube_id: "UCFoSG0in24zEJc09bkO32OQ", name: "IA Cover Manoel Gomes"},
  %{youtube_id: "UCFsVVUvcnAL6gjUvPcYdhEw", name: "mikiilis"},
  %{youtube_id: "UCG4hERGtW4bILUw8SJ62ylQ", name: "ESCAPE"},
  %{youtube_id: "UCG8E2l0hc9LJS_rnMF3rp7g", name: "Electrotechnique"},
  %{youtube_id: "UCGDMcgLb89_NSbRFTQi1VgA", name: "Karat"},
  %{youtube_id: "UCGN8fQ7phq_m689czKVdV8w", name: "Gleeman"},
  %{youtube_id: "UCGapx00cL3gABt3mahYwMBg", name: "TUCA 2"},
  %{youtube_id: "UCGeLPwvfOmMUzpbWCui4lOg", name: "URUBU"},
  %{youtube_id: "UCH9-RQA3S2cgH-PHeyzJPPw", name: "Far Out Recordings"},
  %{youtube_id: "UCHPuhCfAVPt2YKBcqyvnroA", name: "casacájá"},
  %{youtube_id: "UCHdLVKdAeG6zAeZMGZh91bg", name: "Neutrality Studies"},
  %{youtube_id: "UCHp7JxetDzPMDN0xSjOOWqA", name: "Do Noise"},
  %{youtube_id: "UCI1Z201n-8OelkSg0DVOsng", name: "Tweag by Modus Create"},
  %{youtube_id: "UCI9BGORQ8EKmHPwToK9fZQg", name: "DJ Tahira"},
  %{youtube_id: "UCIASTDaUEkDgYhvuau8V8vA", name: "Linglong Mandarin Chinese"},
  %{youtube_id: "UCIDJH27tBTlA7jjMI5wnibA", name: "FromSergio"},
  %{youtube_id: "UCIcg7rU2e5VWJqobAAqQaDg", name: "The Red Delta Project"},
  %{youtube_id: "UCIm5dgSJPmVBkz7CKuGtwFQ", name: "Tongo Oficial"},
  %{youtube_id: "UCIrKT6IOvPo_oT4zSUm6uhQ", name: "elibro"},
  %{youtube_id: "UCIrOOZeidxZjoDRFdLqabmA", name: "Metal Music Theory"},
  %{youtube_id: "UCJBV9SHaDxk5sB5hybc4QvA", name: "Dan Gorelick"},
  %{youtube_id: "UCJETKJUcGsnHNaa_v8z5nKQ", name: "Badi Assad"},
  %{youtube_id: "UCJFxuy0nRF3Z9YvBW7vIjCA", name: "SELVAGEM ciclo de estudos sobre a vida"},
  %{youtube_id: "UCJGXYyy7lhiFa9ytZQrmKwQ", name: "halicon"},
  %{youtube_id: "UCJHA_jMfCvEnv-3kRjTCQXw", name: "Binging with Babish"},
  %{youtube_id: "UCJJvEXCTt1x1adr8hsf3P-g", name: "Bastl Instruments"},
  %{youtube_id: "UCJZzlrV7W46cT3BxfZJzW3w", name: "wavparty"},
  %{youtube_id: "UCJ_ufhZd8W48-_ofWmAfpmw", name: "Tiago Tavares"},
  %{youtube_id: "UCJfWd10swwy-oNdxCWENAHA", name: "Sudden Language"},
  %{youtube_id: "UCK0qhOJXe3slT1ZFS0_0JSQ", name: "Shimmer"},
  %{youtube_id: "UCK5DQ8FJWnI4DMtuoYtXEcg", name: "Mark Ericksen"},
  %{youtube_id: "UCKKkeS1rTswQDHxHXwKz3yg", name: "Nãnan Matos"},
  %{youtube_id: "UCKTmptOuTldks9ixwzYPUFg", name: "dj marky"},
  %{youtube_id: "UCKhnGk6OEu218Dtd37gus-w", name: "D Smoke"},
  %{youtube_id: "UCKtI2EPpyNu27M4BNeCVg9w", name: "perfumerism"},
  %{youtube_id: "UCL4EOZdNVBojiF3CzwqRCKA", name: "Tauri Apps"},
  %{youtube_id: "UCLGNeElk4sNgzUrZr0c9krA", name: "Chef Jean-Pierre"},
  %{youtube_id: "UCLnhktRhhECR6-c1xZP2GjQ", name: "Code Unknown"},
  %{youtube_id: "UCLs9xOXFr1QUsPYcwoylwzw", name: "Acervo Otacilio Batista"},
  %{youtube_id: "UCMYA7_IJr3zkRk1AIp9JjaQ", name: "Hasanabi Better Clips"},
  %{youtube_id: "UCMaHc1Rq2viM88OsluS2WWw", name: "Web Audio Conf"},
  %{youtube_id: "UCMk_WSPy3EE16aK5HLzCJzw", name: "NativLang"},
  %{youtube_id: "UCN1h109PDDp_wYIFsoWmZrQ", name: "Marion Grasby"},
  %{youtube_id: "UCN1zEinAcf5OEQsFlexg5MQ", name: "Ehsan Gelsi"},
  %{youtube_id: "UCN7eGh071dMAEV7PHBgd2pw", name: "TREVO"},
  %{youtube_id: "UCN9v4QG3AQEP3zuRvVs2dAg", name: "History Time"},
  %{youtube_id: "UCNIBhdj9nDs9Ruv36lfHEHw", name: "李祥霆 - Topic"},
  %{youtube_id: "UCNSQb4xRxWnIq05buy6XDiw", name: "George Kaplan"},
  %{youtube_id: "UCNV2eEr4N2DNWv2TC3_EClA", name: "Os três elementos"},
  %{youtube_id: "UCNXvxXpDJXp-mZu3pFMzYHQ", name: "Our Changing Climate"},
  %{youtube_id: "UCN__G2hSqRKuqedN3M0JCDg", name: "Andrewism"},
  %{youtube_id: "UCNbD14SZBQ5e0ddcLY7hVDw", name: "Crédito Sem Mistério"},
  %{youtube_id: "UCNnWgkzPKPgW-1kCLHZ7n0w", name: "Mecha"},
  %{youtube_id: "UCNswqMt34oak0lb7DEmHstA", name: "Maracatech"},
  %{youtube_id: "UCNvfjGiZOuh78KYMojvugeQ", name: "Hyperdub"},
  %{youtube_id: "UCO7b5EvPM9UJLDaO_OXCQrg", name: "Wait But Why"},
  %{youtube_id: "UCOVaYb_JakkTrECenJ4zm9g", name: "Select"},
  %{youtube_id: "UCOa7Pex5ygIftH3hdLAJRTg", name: "NTNU Det humanistiske fakultet"},
  %{youtube_id: "UCOjUlJ4EpPxuhtT0zEVw25A", name: "Opera Mundi"},
  %{youtube_id: "UCOpTD7evpw6HJnvLtsCGTww", name: "pulusound"},
  %{youtube_id: "UCOw-2YYviIJGXgdXej_tJYw", name: "Flavio Rump"},
  %{youtube_id: "UCP2N2yEr8kFJgTOTjDWdbRA", name: "Morning Strategy"},
  %{youtube_id: "UCP5tjEmvPItGyLhmjdwP7Ww", name: "RealLifeLore"},
  %{youtube_id: "UCP9zziS-u29-MkghIFBU0ag", name: "UGREEN Educação "},
  %{youtube_id: "UCPKyCS-U3Hlc_btooHRy-mQ", name: "David Ogborn"},
  %{youtube_id: "UCPPZoYsfoSekIpLcz9plX1Q", name: "Hakim"},
  %{youtube_id: "UCPW3Ugq9WxSKvkJygZJoP0A", name: "Codando Sem Codar - Giampaolo Lepore"},
  %{youtube_id: "UCPb2L7gy8Rbr56JfoHrBEHQ", name: "Enabled"},
  %{youtube_id: "UCPctdXVw8Th9aLH5F6akrFg", name: "onformative"},
  %{youtube_id: "UCQ83chf0Yg1yt5Hrya1uVWQ", name: "TV Grabois"},
  %{youtube_id: "UCQJKfe5Vu10-23oYJA-OHgQ", name: "Curumin"},
  %{youtube_id: "UCQKlrmwFP2flRdjBPoiq8PA", name: "The Saturn Archives"},
  %{youtube_id: "UCQO6Ye70UcqC1rSC_hVAX7A", name: "Talon Fitness"},
  %{youtube_id: "UCQRPDZMSwXFEDS67uc7kIdg", name: "Buenas Ideias"},
  %{youtube_id: "UCQVvmfqjIy94d9z__cafdLQ", name: "davus"},
  %{youtube_id: "UCQWoQ27a6IZAUN-ylpJ_N2g", name: "Bicuda Maculata"},
  %{youtube_id: "UCQimGgtBQmF4zxOdnARWFpg", name: "Tiago Santineli"},
  %{youtube_id: "UCQsu2xQzhmgAZjTn8m8S9VQ", name: "Matheus Mota - Topic"},
  %{youtube_id: "UCQt6cdrMvcEZqM5vRL3zTrw", name: "MediaLab UnB"},
  %{youtube_id: "UCQxy4iV5OiWbnqzkUAVyl-g", name: "Iana Meireles"},
  %{youtube_id: "UCR1ATYyCJML6dxqgQhwIKZg", name: "Cadence Hira"},
  %{youtube_id: "UCR1MEt7EizhxAbxvaLiFJfg", name: "Alexandre Rangel"},
  %{youtube_id: "UCR53qjkj3zz9_rwhhzyXDRg", name: "YACHT"},
  %{youtube_id: "UCRCViAiQjt0MB-2hX5CRIxg", name: "Arthur Fauveau"},
  %{youtube_id: "UCRCq59D6i1aKDjdx91MWimg", name: "Los Pirañas"},
  %{youtube_id: "UCRIZtPl9nb9RiXc9btSTQNw", name: "Food Wishes"},
  %{youtube_id: "UCRTQN476CPDQXFuTwTvz5JA", name: "검치단"},
  %{youtube_id: "UCRcatw-5UfCNkyVUamHfHdQ", name: "Afro Hamurai"},
  %{youtube_id: "UCRwIF4NhKQf6tQpnYDcSC5A", name: "MusicTheoryForGuitar"},
  %{youtube_id: "UCS3yWRfP_AB44vuEC6ptqwA", name: "namgyal"},
  %{youtube_id: "UCS7aoxEiTRtuYjZQTsaAVqg", name: "Alex Campbell"},
  %{youtube_id: "UCSJ5dvIotZjDQP9VD8cJoCg", name: "Tero Parviainen"},
  %{youtube_id: "UCSJR5QVczbr3fEDvwYxagPw", name: "Nala Sinephro"},
  %{youtube_id: "UCSZ46fSVw9uw3h1LhgsFZIQ", name: "ROZALIA"},
  %{youtube_id: "UCSZg7ly3xK6BGODea-3Vw9w", name: "Erik Oostveen"},
  %{youtube_id: "UCSbW9j_JVr6Iyd_yMWv--MQ", name: "Harpyja"},
  %{youtube_id: "UCSqFLjaLZFOEsi8fudGoayQ", name: "Chanvallon François"},
  %{youtube_id: "UCT6AJiTYspOILBK3hMWEq2g", name: "Switch and Click"},
  %{youtube_id: "UCT6Y5JJPKe_JDMivpKgVXew", name: "Fall of Civilizations"},
  %{youtube_id: "UCT9D4yVK5_sWSfmGRNrUXPQ", name: "Element433 (a.k.a. Pere Villez)"},
  %{youtube_id: "UCTOktd_ySjXoyUm97GAPmvw", name: "Paavo - Topic"},
  %{youtube_id: "UCTbGOtK_SzsOWakwnIXbxhQ", name: "The Joy Official Music"},
  %{youtube_id: "UCTcUrFU4wXgoogiA0-Oejmg", name: "Edimar Silva, poesia e parcerias"},
  %{youtube_id: "UCTdw38Cw6jcm0atBPA39a0Q", name: "NDC Conferences"},
  %{youtube_id: "UCTnRtQ9IkBGmCKcLB31BcyA", name: "ICL Notícias "},
  %{youtube_id: "UCTokjkGaFeCFmqAKIu09M8w", name: "CUFA"},
  %{youtube_id: "UCTySJT6WJJ_ORFChOInL7mg", name: "DENNEHY"},
  %{youtube_id: "UCU25jev9bdXdEIzEYXre1xg", name: "DuncanAndrewsMusic"},
  %{youtube_id: "UCU5cjvEHYoBYddQZH-AKnmQ", name: "EVERTON BRITO"},
  %{youtube_id: "UCU6SEVyisqcvoMHVgMRuRNw", name: "Victor Vasconcelos"},
  %{youtube_id: "UCUMZ7gohGI9HcU9VNsr2FJQ", name: "Bloomberg Originals"},
  %{youtube_id: "UCUOosiFLTcefuatdJmE89yA", name: "moistpeace"},
  %{youtube_id: "UCUQn1aOAXulmkAtI-yoaYeg", name: "Nesso"},
  %{youtube_id: "UCUby1u7JsoUedv1eMYZRXPw", name: "Ian R"},
  %{youtube_id: "UCUnFKXgVQxuPbHjxwb61MEA", name: "Attic Space"},
  %{youtube_id: "UCUyE4cXea0ATlynfbjI3xwQ", name: "Dream Distraction"},
  %{youtube_id: "UCUzmizB92LJ9oxf5T_snZNA", name: "BadEmpanada"},
  %{youtube_id: "UCVJpu8m6VUzAEQaDc8Ip3HA", name: "Sacred Phrases"},
  %{youtube_id: "UCVRWkwOQIpxPOhQ9V-gL2UA", name: "SIAMES"},
  %{youtube_id: "UCViOpokxVZxaMEG6V2EMhPw", name: "Tech Nicholson"},
  %{youtube_id: "UCVqqooL0OLCftRt3s_6BBlQ", name: "Joyful Noise Recordings"},
  %{youtube_id: "UCW5R53ckTBE4JJtUmc64lng", name: "BookswithEmilyFox"},
  %{youtube_id: "UCW5pFkwpq0YU1f3Sl-MnTaQ", name: "maudlin of the Well - Topic"},
  %{youtube_id: "UCW8n8TvZccEhXdRogIm_qhg", name: "Sakurambo"},
  %{youtube_id: "UCWABUvm5kI4q-ge8BhDVTag", name: "MusicHub"},
  %{youtube_id: "UCWCk81c_nQOsm5M-xKuTFnQ", name: "Pure Unintentional ASMR"},
  %{youtube_id: "UCWMJ7BD3qrM3OCSAeplDQuQ", name: "Vivi Morais"},
  %{youtube_id: "UCWPOtMwRT7OTUgt3OJLVWvA", name: "Thinman"},
  %{youtube_id: "UCWQz_WTGA9NuCf-_tw9lIVA", name: "The Jacksons"},
  %{youtube_id: "UCWVqQd0rDx4wV_nS-Ou9ciA", name: "Gaby Amarantos"},
  %{youtube_id: "UCW_-i5GrKUoy6dlBJvPtxOg", name: "Thibaut Barrère"},
  %{youtube_id: "UCWm3-VV9uVjU-v4Pc2ZZryQ", name: "imakaiya"},
  %{youtube_id: "UCWquNQV8Y0_defMKnGKrFOQ", name: "Ahrefs"},
  %{youtube_id: "UCWrAIU_pkQs9Ay1-AHFyipg", name: "Alexandra Cárdenas"},
  %{youtube_id: "UCWwyQO3rwWYppJNtTxidCiw", name: "Spacetime Continuum - Topic"},
  %{youtube_id: "UCX2M7xn-jMmq4KfX25TCTCA", name: "HBO Brasil"},
  %{youtube_id: "UCXDIl5ElYimqmasGFGmp7Eg", name: "Story Mode"},
  %{youtube_id: "UCXXVJt6VglSKLojqh8eQ2nQ", name: "Akio Ponte"},
  %{youtube_id: "UCXgxNzAgZ1GExhTW4X1mUrg", name: "Marc Rebillet"},
  %{youtube_id: "UCXsA8gpFTm7w3RhPRTdqXvw", name: "Serrador"},
  %{youtube_id: "UCXsTL23lMHota91Q5qEsJ7Q", name: "Chris McAlister"},
  %{youtube_id: "UCY6VZZo9MZCyIIozTs0khNA", name: "easy, actually"},
  %{youtube_id: "UCYHWTb-jg4Uey4jMsWvQ2Ag", name: "ProbeComposer"},
  %{youtube_id: "UCYVrkMZdrjq5eICOG6Rxiwg", name: "Tecnologia e Classe (TeClas)"},
  %{youtube_id: "UCYn5oKcBQtPVWKznEMCNqoA", name: "MrReason"},
  %{youtube_id: "UCYqCZOwHbnPwyjawKfE21wg", name: "Tensor Programming"},
  %{youtube_id: "UCYu_mLfrpWhJNk9J18hY_Fg", name: "André Bittencourt"},
  %{youtube_id: "UCYwqPUU-QvTl005gAcoO6yA", name: "Glissonic"},
  %{youtube_id: "UCZ3cq54DRgNjYhcqERz5M7g", name: "nokulture"},
  %{youtube_id: "UCZ8__QJzbQCi-6ywoMvAlrw", name: "WAND1N"},
  %{youtube_id: "UCZCT_L-DhD6NIY4Gyoz_7wg", name: "Diário do Mestre"},
  %{youtube_id: "UCZHmQk67mSJgfCCTn7xBfew", name: "Yannic Kilcher"},
  %{youtube_id: "UCZIIRX8rkNjVpP-oLMHpeDw", name: "Calisthenicmovement"},
  %{youtube_id: "UCZYluLIgft1xn0uWLUL0XYQ", name: "Laura Wini"},
  %{youtube_id: "UCZynkoE9qmSdB1hSoeQshTg", name: "Unit: E"},
  %{youtube_id: "UC_9jWF3Xr0KuIIuIIV_q5hA", name: "Lil Data"},
  %{youtube_id: "UC_N48pxd05dX53_8vov8zqA", name: "Eulerroom"},
  %{youtube_id: "UC_QDcEv6kMoVx1tBYy_VDiw", name: "Rodrigo Koshino"},
  %{youtube_id: "UC_T-XITSEX_xUqgfJnyEOKA", name: "Fee Grilo"},
  %{youtube_id: "UC_WA7w7TmccwGEiyRjch2Nw", name: "Phoebe Yu"},
  %{youtube_id: "UC_YLlyOlc9cyPNaC0JdNfmg", name: "Instituto Moreira Salles"},
  %{youtube_id: "UC_pSCYWbMn4JcsxbWOzkgEQ", name: "Rachel Thomas"},
  %{youtube_id: "UC_rhtDUqaWoHZoYiz1AUzbg", name: "Sunni Colón"},
  %{youtube_id: "UC_zQ777U6YTyatP3P1wi3xw", name: "NEVER TOO SMALL"},
  %{youtube_id: "UCa64zeq5HO-xqMp3DbQWB-Q", name: "Modou Touré"},
  %{youtube_id: "UCaH-GkYSXaSaGML0gAqHu0g", name: "nickjitsu"},
  %{youtube_id: "UCaNGmT_k_nXSflpP3-QaUBQ", name: "Sound Affects"},
  %{youtube_id: "UCahVqJcPfPInkmw2Zt9_7uA", name: "Fusion & Jazz Finger Drum"},
  %{youtube_id: "UCaum_fMDGgFQCmKHUBPq_xg", name: "Radiolab"},
  %{youtube_id: "UCb-LtZ6vnj0hu7aGq1sfFfQ", name: "Umanesimo Artificiale"},
  %{youtube_id: "UCb3cDvWiHwRzQaK81PrISbg", name: "Leeja Miller"},
  %{youtube_id: "UCbAn7pVK2VIyo-UysfWGdZQ", name: "ui․dev"},
  %{youtube_id: "UCbBsRNBEBu5IRGdksCDvr5A", name: "Gyasi Linje"},
  %{youtube_id: "UCbRP3c757lWg9M-U7TyEkXA", name: "Theo - t3․gg"},
  %{youtube_id: "UCbTEF6-Occ7j4C44RNeR4vQ", name: "Johan von Konow"},
  %{youtube_id: "UCbTs-DV6WhfkRvaa_Ta8p3Q", name: "Ghales - Topic"},
  %{youtube_id: "UCbVkp_ZQus6ExLcK4Z2HLQg", name: "chaosprint"},
  %{youtube_id: "UCbfYPyITQ-7l4upoX8nvctg", name: "Two Minute Papers"},
  %{youtube_id: "UCbkPir_J3rdrtAriiNIFzBA", name: "a engrenagem"},
  %{youtube_id: "UCc6K_BMz6T3ZxOVKbl6kJrQ", name: "Kwaidanrecords"},
  %{youtube_id: "UCcDohjrcmr2mPyYrpuQoZaQ", name: "GATIVIDEO"},
  %{youtube_id: "UCcGlLQgO9bzynCw6TYj1qnQ", name: "Music with Myles"},
  %{youtube_id: "UCccX2-oylEl-x9fTeHK4hqg", name: "walnutcon"},
  %{youtube_id: "UCcoxGCRGcq6FhHbEvr2y9Vg", name: "Ian Neves - História Pública"},
  %{youtube_id: "UCcqABzYjM7gBxhizPzg6ooA", name: "bcacciaaudio"},
  %{youtube_id: "UCcwsKzSQ1SNBcdG-kl7X-Tw", name: "Fragrance Xpress - Halysson Abreu"},
  %{youtube_id: "UCd2KNtfphz8HvYzM4pwtHmg", name: "triple j"},
  %{youtube_id: "UCd8sdpZhDOqoBiwvsSrwrkg", name: "Adam Frater"},
  %{youtube_id: "UCdBK94H6oZT2Q7l0-b0xmMg", name: "ShortCircuit"},
  %{youtube_id: "UCdJKNWduQ7gz8vvJy79XuzQ", name: "Cultivando"},
  %{youtube_id: "UCdYnL5uXF-sIddK4BpSy2Fw", name: "Audino vilão"},
  %{youtube_id: "UCdaByoavthEiWrQNSA6v8hA", name: "Synaesmedia : Creative Coding"},
  %{youtube_id: "UCdrqrIa6sCvnDucHxOs1zrg", name: "Secretly Canadian"},
  %{youtube_id: "UCdyPkcbix5sQsch8BBoeFBQ", name: "Oumou Sangaré"},
  %{youtube_id: "UCe7gKlCHL5vzhgp5p4S_Qvg", name: "Amaro Freitas"},
  %{youtube_id: "UCeJFgNahi--FKs0oJyeRDEw", name: "Hybrid Calisthenics"},
  %{youtube_id: "UCeLwY_iqGhtq3AIdAEvT9-g", name: "Parabólica"},
  %{youtube_id: "UCeTfBygNb1TahcNpZyELO8g", name: "Jacob Geller"},
  %{youtube_id: "UCeV8EyNpF56e8E_GXo9YSFw", name: "Torotumbo"},
  %{youtube_id: "UCeVbrw-tfahYgt6yQaoLtXg", name: "ふぐりたつお"},
  %{youtube_id: "UCekQr9znsk2vWxBo3YiLq2w", name: "You Suck At Cooking"},
  %{youtube_id: "UCeyJbY9g9spG7u8kfs2WrwQ", name: "Processing Foundation"},
  %{youtube_id: "UCf5OjKkBMMXyVrowbMsIQYQ", name: "Jota Dale"},
  %{youtube_id: "UCf6Xg2aTl9r4xOmE7zcB13g", name: "Horta do Ditian"},
  %{youtube_id: "UCfGzRYv-mVr02U4zMlPvxcA", name: "Zé Krishna"},
  %{youtube_id: "UCfRh_MUIlNaMyizKwDhN9Jw", name: "redesdenadie"},
  %{youtube_id: "UCfWdGyZaZODBPQc9Lu0y6aw", name: "Ola Englund"},
  %{youtube_id: "UCfWybrB-Faa30sXUE6eqMIQ", name: "Zarfen the Loot Goblin"},
  %{youtube_id: "UCfXNMu0pgaQjC02hGE0ilnQ", name: "Alberto Martinez Del Rio Guitar"},
  %{youtube_id: "UCfoU40VVjWEQNzf9pipMA-g", name: "The Pop Descriptivist"},
  %{youtube_id: "UCg0g5ULQS1Tr2N3Oy00-N1w", name: "Arly Cravo"},
  %{youtube_id: "UCgG5R7mj7cN6bGvkJXPOidg", name: "House of Mythology"},
  %{youtube_id: "UCgHhJsZZYFwpJK976ctvJ2A", name: "Patchblocks"},
  %{youtube_id: "UCgb_TbreMgfDdLKkr4yYJHw", name: "Andrew Millison"},
  %{youtube_id: "UCgi2u-lGY-2i2ubLsUr6FbQ", name: "F.D Signifier"},
  %{youtube_id: "UCgvg86OqagNMJdCQne5adGg", name: "Canal Jota Dale"},
  %{youtube_id: "UCh-jKy1T-XGYW-XUg4ZCZwQ", name: "i’m waiting"},
  %{youtube_id: "UCh1DHhmh57-qtBIYMupmt3w", name: "Meu Nome é Correria"},
  %{youtube_id: "UChLf17APcOi5Zar4yknIpow", name: "Anna"},
  %{youtube_id: "UChXwDMCof1lYPBsxNPuAPUw", name: "Processing Community Japan"},
  %{youtube_id: "UChd9uQdJAWEXQoq-jiPP__Q", name: "Charlie Looker"},
  %{youtube_id: "UChqe--qhcErjPjCA9oJgq0w", name: "Algorave Brasil"},
  %{youtube_id: "UCiER8p540j2SosO7OX7E0VA", name: "Legends of Avantris"},
  %{youtube_id: "UCiHJWmDw3tSgdqy_5OVOkGg", name: "Peter “Danish Pete” Honoré"},
  %{youtube_id: "UCiM26SqidvoOp_RBs430jig", name: "Vague Robots"},
  %{youtube_id: "UCiT9RITQ9PW6BhXK0y2jaeg", name: "Ken Jee"},
  %{youtube_id: "UCiWnEgWIBiPE04ahBRFGXSg", name: "Nik Bärtsch - Topic"},
  %{youtube_id: "UCiYs0uDOI-S3qmpoUt8Ax4w", name: "Tom Suassuna"},
  %{youtube_id: "UCidn-1Q_KX7hCwZctFYuiGw", name: "Jorge Albuquerque"},
  %{youtube_id: "UCiwnEsZwpEZ9wiSsgv9ytKQ", name: "VESGO"},
  %{youtube_id: "UCj4SiKeulWS3Sk3fdlF5uWA", name: "Dusty Patches"},
  %{youtube_id: "UCjC-h_-Ytzjiy5wZbxeQKgg", name: "Extensão UnB"},
  %{youtube_id: "UCjExK5PA9MMPPqf3ZWL464g", name: "Renato Galv Santos"},
  %{youtube_id: "UCjSEJkpGbcZhvo0lr-44X_w", name: "TechHut"},
  %{youtube_id: "UCjSFU-9JUt2ATyjomcsRgSQ", name: "Jean Tux"},
  %{youtube_id: "UCjbOCVqp-YIA2lRr0KsfCTA", name: "Up Learn"},
  %{youtube_id: "UCjewxGh1Gx5i5Uzxn0v-TPw", name: "The Punk Rock MBA"},
  %{youtube_id: "UCjld0RwLdJsIq6U-9x_SW3w", name: "TOPLAP_BARCELONA"},
  %{youtube_id: "UCjoikcHmbQ9LRK6URiKKMzg", name: "YPU"},
  %{youtube_id: "UCjr2bPAyPV7t35MvcgT3W8Q", name: "The Hated One"},
  %{youtube_id: "UCjs8aDIYQTNuxIctdX4_OdQ", name: "Emmanuel Horvilleur"},
  %{youtube_id: "UCk5N0NKADTUjUIvgyySs-fQ", name: "Matheus Mota"},
  %{youtube_id: "UCkIEY6rUSPy4qQjLqBBLUSg", name: "Via Infinda"},
  %{youtube_id: "UCkIQAtYnvo4TptAazSx0FWA", name: "Leod"},
  %{youtube_id: "UCkL4v-tohdDZX7kzmL9b2UA", name: "John Nathan Cordy"},
  %{youtube_id: "UCkWbqlDAyJh2n8DN5X6NZyg", name: "Data Is Beautiful"},
  %{youtube_id: "UCkWu5WFf4EYsiV0zepVJ_ww", name: "Rich Brian"},
  %{youtube_id: "UCkd_P4COxwxPkcMxr0gNK9Q", name: "Melissa 'Splains The Classics"},
  %{youtube_id: "UCkmpC9Tqr1MUEcDK9Ie80Jw", name: "Mouts (Sua Mãe)"},
  %{youtube_id: "UClGZuFQOesn7E2fvp8pm0kQ", name: "Estudio Laje"},
  %{youtube_id: "UClZD_U26ArAGNTAGpzsv9Xg", name: "Meno"},
  %{youtube_id: "UClqVAKKbtvJMDkvJ5ym_e1w", name: "TheTechnobear"},
  %{youtube_id: "UClqzYKNNfbdWtxgFwBqnEsg", name: "KOOP Instruments"},
  %{youtube_id: "UClsFdM0HzTdF1JYoraQ0aUw", name: "Brick Experiment Channel"},
  %{youtube_id: "UCmGKyJ8CjTVe06dXjYNixzg", name: "ThomasGrillo"},
  %{youtube_id: "UCmM3eCpmWKLJj2PDW_jdGkg", name: "LeadDev"},
  %{youtube_id: "UCmQXOAse-VnzuXHebX5I77g", name: "Charlotte McDonnell"},
  %{youtube_id: "UCmaezCh5e5PhiAc04Re_0mA", name: "Rodrigo dos Santos Melo"},
  %{youtube_id: "UCmdtMVA4uq2LJliikUCwNbQ", name: "Carl Colglazier"},
  %{youtube_id: "UCmojzDyzvW_Sev7ZTI5CT3A", name: "KIRINJI"},
  %{youtube_id: "UCmopeXHb16dHZHI6qRWWkXg", name: "hate5six"},
  %{youtube_id: "UCn0vuDgN_Z7IPeTiXwjsxzA", name: "Maurice Moves"},
  %{youtube_id: "UCn5fhcGRrCvrmFibPbT6q1A", name: "Brian Lagerstrom "},
  %{youtube_id: "UCnB9f1dsU_FUdZ9m-Xukdxw", name: "Herman Clebanoff & His Orchestra - Topic"},
  %{youtube_id: "UCnLdHOuue5i1O7TsH6oh07w", name: "BrazilJS"},
  %{youtube_id: "UCnxrdFPXJMeHru_b4Q_vTPQ", name: "Simply Explained"},
  %{youtube_id: "UCo2qyASfqPOhKEf1mn1Runw", name: "Mayer János"},
  %{youtube_id: "UCoEKOXb87uOlkCNO0eoPfEA", name: "Leonardo Rafael"},
  %{youtube_id: "UCoWTCEbunHmsHJx_iBN4Ktw", name: "German Velasco"},
  %{youtube_id: "UCoWkEriHgWGqxHVcoklTNJQ", name: "Emiliano Grilli"},
  %{youtube_id: "UCoYRWFWlxTmiQLNcAuM9juA", name: "CIC UnB"},
  %{youtube_id: "UCojm9doQ4Nhbaz_4ehIJ5TQ", name: "Tobias Pisani"},
  %{youtube_id: "UCoyyLyZP36tkevG7AQc94ig", name: "Ｌａｎ"},
  %{youtube_id: "UCpOiPAD4gNK0PifmtTOv6sQ", name: "Running Remote"},
  %{youtube_id: "UCpScOpAyHB28Sj7oy32Azrg", name: "Seu Estrelo e o Fuá do Terreiro"},
  %{youtube_id: "UCpn3JDMUCSudVFC2x4uZWyA", name: "Ben Gold"},
  %{youtube_id: "UCq-V8B_t_gUWlAJ5YaJSRzQ", name: "revista piauí"},
  %{youtube_id: "UCq6aw03lNILzV96UvEAASfQ", name: "bill wurtz"},
  %{youtube_id: "UCq9bA7W80jKxUO1vPRwB24Q", name: "Rc Ballerini"},
  %{youtube_id: "UCqBY-VQ2BxHOWnVpuC7swrw", name: "NORMOSE"},
  %{youtube_id: "UCqJ-Xo29CKyLTjn6z2XwYAw", name: "Game Maker's Toolkit"},
  %{youtube_id: "UCqKjl-xepqcSTkJGR9pq_vQ", name: "RIO4FUN"},
  %{youtube_id: "UCqNkn5PNeSqbQTAR5RP-L-Q", name: "Andy Cooks"},
  %{youtube_id: "UCqVFXfZS7ZCNUQEp29oihXA", name: "Kowloon"},
  %{youtube_id: "UCqbz_4hrf2D58UFBOleuFnQ", name: "Gustavo Gaiofato | História Cabeluda"},
  %{youtube_id: "UCqpmK99bVcBsa8G5s7FeBQQ", name: "justleroy synths&sequences"},
  %{youtube_id: "UCr-dKD-HxGcJq4IhuePv35g", name: "Novíssimo Edgar"},
  %{youtube_id: "UCrCTC5_t-HaVJ025DbYITiw", name: "Alice Cappelle"},
  %{youtube_id: "UCrLmG6QSeI_0TTibp_1pIXw", name: "Psionic Audio"},
  %{youtube_id: "UCrSRmPjjJiawVWHO_4LpkIA", name: "scrobbles by DJ GUNBOUND"},
  %{youtube_id: "UCs-kEyKdvH2sBZMbxUd7nyQ", name: "Canastra Records"},
  %{youtube_id: "UCs3d1Sh4WW4ZfIVO312x-Dw", name: "Eulerroom test"},
  %{youtube_id: "UCsBjURrPoezykLs9EqgamOA", name: "Fireship"},
  %{youtube_id: "UCs_XQN1c4YYpR02JeDeNm9Q", name: "Include"},
  %{youtube_id: "UCshObcm-nLhbu8MY50EZ5Ng", name: "Benn Jordan"},
  %{youtube_id: "UCt3B6rUXb__X2eMyY7jzgIg", name: "Bullet Journal"},
  %{youtube_id: "UCtQVQIgKdxGTpM1ynAPIwyg", name: "QCGInteractiveMusic"},
  %{youtube_id: "UCtUTlOdao4lCm6R8PkLg5ng", name: "Snupps Synth channel"},
  %{youtube_id: "UCtc5INMrIDrDEbv2FLK4bVg", name: "Natalie Chami"},
  %{youtube_id: "UCtoaZpBnrd0lhycxYJ4MNOQ", name: "HasanAbi"},
  %{youtube_id: "UCtqxG9IrHFU_ID1khGvx9sA", name: "All Gas No Brakes"},
  %{youtube_id: "UCu0Ynxpk6fQFJ_HSnWYLmDw", name: "Shingo Tamagawa"},
  %{youtube_id: "UCu1R-PodIMk0liS7OGSUboQ", name: "Jay Hosking"},
  %{youtube_id: "UCu9fyQiWWdUH38r6wRgsFUw", name: "Caçadores de Ofertas"},
  %{youtube_id: "UCuCdB1TlQbsWwHpjeSLAjxg", name: "Mensla"},
  %{youtube_id: "UCuVuYmvwHJLtRfpXphPFm2w", name: "Felipe Durante"},
  %{youtube_id: "UCuXRVjqgXCWkMSdlgwT3Umg", name: "Jackson Marinho"},
  %{youtube_id: "UCuaogbzXyHLN0rWrqNpMwig", name: "Prince Ausuma Malaika"},
  %{youtube_id: "UCv48AhVgiiRqDk30EZSbnMg", name: "Joenio Marques da Costa"},
  %{youtube_id: "UCv54ZOBigseC6X5i1rr5fFw", name: "satoruki"},
  %{youtube_id: "UCv677TvmG-LAYr6FyTSCsKw", name: "Ellen Oléria"},
  %{youtube_id: "UCvJVDYK4cxaKjG1qyRMC9mg", name: "Pedro Francisco"},
  %{youtube_id: "UCvUl78m9jK6IYPQVkFIsf7g", name: "liam"},
  %{youtube_id: "UCvcQ3EzFRohTOtqAyZcS5gA", name: "Cindygod - Topic"},
  %{youtube_id: "UCveiUrXh96I4-1h5loAE2Mg", name: "Digital Routine"},
  %{youtube_id: "UCviKKPyIrxvADia_OUbW1jw", name: "Captain Pikant"},
  %{youtube_id: "UCvjgXvBlbQiydffZU7m1_aw", name: "The Coding Train"},
  %{youtube_id: "UCvlxvODp-1uVNco1y8qtz3g", name: "hashi8873"},
  %{youtube_id: "UCvpDFocbB5kLrQkO-ZFzeeQ", name: "Channel 7"},
  %{youtube_id: "UCvu0_g8mlpsXbqZhWHhhCGA", name: "Coletivo Encripta"},
  %{youtube_id: "UCw7ZPiQ5vqp8DICGAwqMK0Q", name: "Prajwal Mahesh"},
  %{youtube_id: "UCw8gC06oOjUtA553wNXO5jw", name: "Filipe Boni"},
  %{youtube_id: "UCwLxgZHR8oDOzJXtXuSB_bA", name: "Indie Playlists"},
  %{youtube_id: "UCwND7cbR0H74oougSzMh3YA", name: "Meridian Brothers"},
  %{youtube_id: "UCwghQysyNdstRfv8YUPyglw", name: "ossia"},
  %{youtube_id: "UCwkt8gzurBsymbE7d1h0V9A", name: "Elisha Kang(엘리샤 강)"},
  %{youtube_id: "UCwzv5N3Z6Y3Tk-c1RibBnkQ", name: "Rádio Novelo"},
  %{youtube_id: "UCxD2E-bVoUbaVFL0Q3PvJTg", name: "ChefSteps"},
  %{youtube_id: "UCxHcoI9ndIdAihEB7ODTOfQ", name: "Trash Theory"},
  %{youtube_id: "UCxKS_QjhJAfV2hgLYxxGkWA", name: "The Avalanches"},
  %{youtube_id: "UCxLYtICsUCWdr1YPrj5DtwA", name: "Ordinary Things"},
  %{youtube_id: "UCxnG945Ig14ePUdKz6wfdOg", name: "Balaclava Records"},
  %{youtube_id: "UCxrmpiKC7STaDpgWQBwwGMA", name: "Science of Loud"},
  %{youtube_id: "UCxtOFcdICmt0-oqYbWlzj7A", name: "Bruno Rohde"},
  %{youtube_id: "UCxxw51w9d_utTp0VNyyG9IA", name: "aini"},
  %{youtube_id: "UCy1hRH78K-J3Jikk9QtBacw", name: "TiranosTembladTV"},
  %{youtube_id: "UCy810FRxbrv5kJ6ShcTzODQ", name: "Coffee & Guitar with Darin Bergsven"},
  %{youtube_id: "UCyBkJxaq9ll-grxvEA2O6XQ", name: "Accordion covers and folk songs"},
  %{youtube_id: "UCyNtlmLB73-7gtlBz00XOQQ", name: "Folding Ideas"},
  %{youtube_id: "UCyQrL08LlvUHcl6snYDfo7g", name: "introvertedmadness"},
  %{youtube_id: "UCyU7tcNimViKY9ne5MFwjXw", name: "Richard Scott"},
  %{youtube_id: "UCyYB-33IjmYy20he8jWuexg", name: "O Cientista Perdido"},
  %{youtube_id: "UCybBViio_TH_uiFFDJuz5tg", name: "Einzelgänger"},
  %{youtube_id: "UCyqCwyBJ98fR-CPoyXUxY5w", name: "Nerd Musician"},
  %{youtube_id: "UCzIohAebCV23WG_RHQlDbHQ", name: "Henrique Souza"},
  %{youtube_id: "UCzUnnTafOoJk5qzCTNUiXAg", name: "Estúdio Naquele Lugar"},
  %{youtube_id: "UCzdg4pZb-viC3EdA1zxRl4A", name: "Hundred Rabbits"},
  %{youtube_id: "UCzrOVL8MeVbleImcTKYdrIA", name: "Andrew Kilpatrick"}
]

scraped_channels = [
  %{youtube_id: "UCuVuYmvwHJLtRfpXphPFm2w", name: "Felipe Durante"},
  %{youtube_id: "UCsBjURrPoezykLs9EqgamOA", name: "Fireship"},
  %{youtube_id: "UCrCTC5_t-HaVJ025DbYITiw", name: "Alice Cappelle"},
  %{youtube_id: "UCqbz_4hrf2D58UFBOleuFnQ", name: "Gustavo Gaiofato | História Cabeluda"},
  %{youtube_id: "UCq-V8B_t_gUWlAJ5YaJSRzQ", name: "revista piauí"},
  %{youtube_id: "UCmopeXHb16dHZHI6qRWWkXg", name: "hate5six"},
  %{youtube_id: "UCkIEY6rUSPy4qQjLqBBLUSg", name: "Via Infinda"},
  %{youtube_id: "UCkmpC9Tqr1MUEcDK9Ie80Jw", name: "Mouts (Sua Mãe)"},
  %{youtube_id: "UClGZuFQOesn7E2fvp8pm0kQ", name: "Estudio Laje"},
  %{youtube_id: "UCiER8p540j2SosO7OX7E0VA", name: "Legends of Avantris"},
  %{youtube_id: "UCiHJWmDw3tSgdqy_5OVOkGg", name: "Peter “Danish Pete” Honoré"},
  %{youtube_id: "UCgi2u-lGY-2i2ubLsUr6FbQ", name: "F.D Signifier"},
  %{youtube_id: "UCgvg86OqagNMJdCQne5adGg", name: "Canal Jota Dale"},
  %{youtube_id: "UCcoxGCRGcq6FhHbEvr2y9Vg", name: "Ian Neves - História Pública"},
  %{youtube_id: "UCbfYPyITQ-7l4upoX8nvctg", name: "Two Minute Papers"},
  %{youtube_id: "UCbRP3c757lWg9M-U7TyEkXA", name: "Theo - t3․gg"},
  %{youtube_id: "UCb3cDvWiHwRzQaK81PrISbg", name: "Leeja Miller"},
  %{youtube_id: "UC_zQ777U6YTyatP3P1wi3xw", name: "NEVER TOO SMALL"},
  %{youtube_id: "UCYVrkMZdrjq5eICOG6Rxiwg", name: "Tecnologia e Classe (TeClas)"},
  %{youtube_id: "UCP9zziS-u29-MkghIFBU0ag", name: "UGREEN Educação "},
  %{youtube_id: "UCMYA7_IJr3zkRk1AIp9JjaQ", name: "Hasanabi Better Clips"},
  %{youtube_id: "UCK5DQ8FJWnI4DMtuoYtXEcg", name: "Mark Ericksen"},
  %{youtube_id: "UCJHA_jMfCvEnv-3kRjTCQXw", name: "Binging with Babish"},
  %{youtube_id: "UCEzJtFWNg7d7TZW7K9JyXmw", name: "Phillip McKnight"},
  %{youtube_id: "UCDqaefcFrSnkKFZwIrKk4Fw", name: "Laurence Harrison"},
  %{youtube_id: "UCBa659QWEk1AI4Tg--mrJ2A", name: "Tom Scott"},
  %{youtube_id: "UCAMExYqcweM7PUebKfmLdFA", name: "Ian Neves"},
  %{youtube_id: "UCCD93px0UneWNFg_HxV4naQ", name: "DESCE A LETRA SHOW"},
  %{youtube_id: "UC7-Pp09PJX_SYP9oyMzUAtg", name: "João Carvalho"},
  %{youtube_id: "UC6-ymYjG0SU0jUWnWh9ZzEQ", name: "Wisecrack"},
  %{youtube_id: "UC53tme8fwwfiNs8WubMwC6g", name: "Felipe Durante pelo mundo"},
  %{youtube_id: "UC3qAUf53j_dUv09jH7jsUJw", name: "Humberto Matos"},
  %{youtube_id: "UC4aiJNDUviw_vMhdCq5Kq1Q", name: "Cortes do Casimito [OFICIAL]"},
  %{youtube_id: "UC28n0tlcNSa1iPe5mettocg", name: "voidzilla"},
  %{youtube_id: "UC2PA-AKmVpU6NKCGtZq_rKQ", name: "Philosophy Tube"}
]
